version: '3.4'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=src.config.DevelopmentConfig
